version: '3'
services:
  fhem:
    build: .
    image: thirstyspace/docker-fhem
    restart: always
    ports:
     - "8083:8083"
     - "8084:8084"
     - "8085:8085"
    volumes:
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime
     - ./fhem.cfg:/opt/fhem/fhem.cfg
    devices:
     - "/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0"
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
